apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../base/podinfo
  - ../base/account
patchesStrategicMerge:
  - podinfo-values.yaml
  - account-values.yaml
